version: '3'
services:
  web:
    build: .
    command: gunicorn -c gunicorn.conf.py escola_manager.wsgi:application
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - media_volume:/workspace/media
    environment:
      - DJANGO_SETTINGS_MODULE=escola_manager.settings
      - MEDIA_ROOT=/workspace/media

volumes:
  static_volume:
  media_volume: