version: '3'
services:
  web:
    build: .
    command: gunicorn -c gunicorn.conf.py escola_manager.wsgi:application
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=escola_manager.settings

volumes:
  static_volume:
  media_volume: