# Generated by Django 4.2.19 on 2025-03-14 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_delete_aluno'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(blank=True, max_length=100, null=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('smtp_server', models.CharField(blank=True, max_length=100, null=True)),
                ('smtp_port', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Configurações do Site',
                'verbose_name_plural': 'Configurações do Site',
            },
        ),
    ]
