# Generated by Django 4.2.19 on 2025-05-22 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('professores', '0002_add_disciplina'),
        ('professores', '0002_disciplina_atribuicaodisciplina'),
    ]

    operations = [
    ]
