# Generated by Django 4.2.19 on 2025-05-22 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('professores', '0003_merge_20250522_1158'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='atribuicaodisciplina',
            options={'verbose_name': 'Atribuição de Disciplina', 'verbose_name_plural': 'Atribuições de Disciplinas'},
        ),
        migrations.AlterModelOptions(
            name='disciplina',
            options={'verbose_name': 'Disciplina', 'verbose_name_plural': 'Disciplinas'},
        ),
    ]
