# Generated by Django 4.2.19 on 2025-05-22 16:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('professores', '0006_add_data_nascimento_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disciplina',
            name='carga_horaria',
        ),
        migrations.AddField(
            model_name='disciplina',
            name='carga_horaria_finais',
            field=models.IntegerField(default=0, verbose_name='Carga Horária - Anos Finais'),
        ),
        migrations.AddField(
            model_name='disciplina',
            name='carga_horaria_iniciais',
            field=models.IntegerField(default=0, verbose_name='Carga Horária - Anos Iniciais'),
        ),
        migrations.AlterField(
            model_name='professor',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
