# Generated by Django 4.2.19 on 2025-03-08 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='version',
            field=models.BigIntegerField(default=1, editable=False),
        ),
    ]
