# Generated by Django 4.2.19 on 2025-05-04 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0002_alter_data_matricula_nullable'),
        ('alunos', '0003_alter_aluno_id'),
        ('alunos', 'make_data_nascimento_nullable'),
    ]

    operations = [
    ]
